name       : elisa
version    : 22.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/elisa-22.04.2.tar.xz : dbc44da077022b2c2d1ea8b9f000a4c5b56a3d2b8e9f0227d64fa5d153850036
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - baloo-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
rundeps    :
    - breeze-icons
    - kirigami2
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
