name       : elisa
version    : 22.12.1
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/elisa-22.12.1.tar.xz : ae64f04a5ccf936e9cba31d4c9b81688e9d4d98e9dcddc1e1ef1a57fc50e91fb
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - baloo-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
rundeps    :
    - breeze-icons
    - kirigami2
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
