name       : elisa
version    : 19.12.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/elisa-19.12.0.tar.xz : 0c4a4ab6535839d8fb7f76febafa571876bb9f2378093d7370b58d341dae42a5
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
