name       : elisa
version    : 20.04.2
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/elisa-20.04.2.tar.xz : d46b8eab27aa183362d6298dacbcec04e57126f25b122f1db31f6819f42dd893
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
    - kwindowsystem-devel
rundeps    :
    - breeze-icons
    - kirigami2
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
