name       : elisa
version    : 21.08.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/elisa-21.08.0.tar.xz : d57b46c0d1518b50f2875c5eca20006389f64e91560146fda7f0a87852e7f493
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - baloo-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
rundeps    :
    - breeze-icons
    - kirigami2
setup      : |
    %patch -p1 -i $pkgfiles/fix-kio-build.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
