name       : elisa
version    : 22.04.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/elisa-22.04.3.tar.xz : 68c64892712446eb4a75b903d8903514f4b2b30d1d1d3a1b34ceececbd3a50ec
license    : LGPL-3.0-or-later
component  : multimedia.audio
summary    : Music player from KDE
homepage   : https://community.kde.org/Elisa
description: |
    Elisa is a simple music player aiming to provide a nice experience for its users. Elisa allows to browse music by album, artist or all tracks. The music is indexed using either a private indexer or an indexer using Baloo.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - baloo-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - kpackage-devel
rundeps    :
    - breeze-icons
    - kirigami2
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
